# General settings
[window]
padding = { x = 2, y = 2 }
dimensions = { columns = 85, lines = 21 }

# Font settings
[font]
normal = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0

# Cursor settings
[cursor]
style = "Beam"

# Colors
[colors]
primary = { background = "0x1e1e1e", foreground = "0xd0cfcc" }
cursor = { text = "0x000000", cursor = "0xd0cfcc" }
selection = {text="0x757575" , background = "0x032231" }
normal = { black = "0x282c4b", red = "0x21aa99", green = "0x3c7885", yellow = "0x71acb7", blue = "0x71acb7", magenta = "0x436f88", cyan = "0x30a2a0", white = "0xaee3ef" }
bright = { black = "0x5e5c64", red = "0x2acdcd", green = "0x042555", yellow = "0x125a5c", blue = "0x29558c", magenta = "0x552de3", cyan = "0x3496a5", white = "0xffffff" }

