# General settings
[window]
padding = { x = 2, y = 2 }
dimensions = { columns = 85, lines = 21 }

# Font settings
[font]
normal = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0

# Cursor settings
[cursor]
style = "Beam"

# Colors
# General settings
# Colors
[colors]
primary = { background = "0x101010", foreground = "0xd0d0d0" }
cursor = { text = "0x000000", cursor = "0xd0d0d0" }
selection = { text = "0x757575", background = "0x424242" }
normal = { black = "0x1c1c1c", red = "0x3c3c3c", green = "0x585858", yellow = "0x747474", blue = "0x909090", magenta = "0xb0b0b0", cyan = "0xd0d0d0", white = "0xe0e0e0" }
bright = { black = "0x484848", red = "0x626262", green = "0x7e7e7e", yellow = "0x999999", blue = "0xb3b3b3", magenta = "0xd5d5d5", cyan = "0xe0e0e0", white = "0xffffff" }

